#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.ls -> dist/index.js ..."
npx lsc -cp --no-header src/index.ls > dist/index.js
echo "build src/index.styl -> dist/index.css ..."
npx stylus -p src/index.styl > dist/index.css
echo "minifying index.js ..."
npx uglifyjs dist/index.js > dist/index.min.js
echo "minifying index.css ..."
npx uglifycss dist/index.css > dist/index.min.css
echo "Copy src/index.pug to dist/index.pug..."
cp src/index.pug dist/index.pug
echo "copy assets to dist/... "
echo "copy files to web/... "
rm -rf web/static/assets/lib/@xlfont/choose/
mkdir -p web/static/assets/lib/@xlfont/choose/dev
cp -R dist/* web/static/assets/lib/@xlfont/choose/dev
echo "done."
