#!/usr/bin/env bash
mkdir -p dist
echo "build src/choosefont.ls -> dist/choosefont.js ..."
./node_modules/.bin/lsc -cbp src/choosefont.ls > dist/choosefont.js
echo "build src/choosefont.styl -> dist/choosefont.css ..."
./node_modules/.bin/stylus -p src/choosefont.styl > dist/choosefont.css
echo "minifying choosefont.js ..."
./node_modules/.bin/uglifyjs dist/choosefont.js > dist/choosefont.min.js
echo "minifying choosefont.css ..."
./node_modules/.bin/uglifycss dist/choosefont.css > dist/choosefont.min.css
echo "Copy src/choosefont.pug to dist/choosefont.pug..."
cp src/choosefont.pug dist/choosefont.pug
echo "copy assets to dist/... "
mkdir -p dist/fontinfo
cp tool/assets/* dist/fontinfo/
echo "copy files to web/... "
mkdir -p web/static/assets/fontinfo
cp -R dist/* web/static/assets/
cp tool/assets/* web/static/assets/fontinfo/
echo "done."
